name: KSRLobbyClient
version: '1.1'
main: ch.ksrminecraft.kSRLobbyClient.KSRLobbyClient
api-version: '1.21'
authors: [ Timy Liniger ]
description: writes rankpoint to global DB
website: https://ksrminecraft.ch/
commands:
  echotest:
    description: Führt einen Echotest zum Proxy aus
    usage: /echotest
    permission: ksrlobbyclient.echotest

  joingame:
    description: Sendet eine Minigame-Join-Anfrage an den Proxy
    usage: /joingame <ziel>

permissions:
  ksrlobbyclient.echotest:
    description: Erlaubt die Nutzung von /echotest
    default: op